One = float(input("Number one: "))
Operation = input("Operation? Example: +: "))
Two = float(input("Number two: "))
print(OneOperationTwo)
print("If you want to add more numbers to this basic script, just modify it. ")
if Operation == "+" : print(One+Two)
elif Operation == "-" : print(One-Two)
elif Operation == "/" : print(One/Two)
elif Operation == "*" : print(One*Two)
